############################################################
#
# article 静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://root:root@192.168.145.132:27017
      database: imooc-news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 192.168.145.132
    port: 5672
    username: guest
    password: guest
    virtual-host: imooc-news-dev
#  zipkin:
#    # 配置zipkin采集的服务地址，数据发送到哪里
#    base-url: http://192.168.145.132:9411/
#    sender:
#      # 数据传输方式，通过web http形式
#      type: web
#  sleuth:
#    sampler:
#      # 设定采样比例，0~1
#      probability: 1
# 定义freemarker生成的html位置
freemarker:
  html:
    target: D:/DevelopProject/freemarker_html
    article: D:/apache-tomcat-9.0.38/webapps/imooc-news/portal/a

############################################################
#
# eureka配置信息
#
############################################################

eureka:
  # 自定义eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
#      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/