############################################################
#
# 搜索服务
# web访问端口号  约定：8007
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
  port: 8007

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-search

  data:
    elasticsearch:
      cluster-name: imooc-elasticsearch
      cluster-nodes: 192.168.145.132:9300
